### ISSUE TITLE
GPL-3.0 license does not allow for "private" website

### ISSUE THREAD

**Issue by cconcannon** [rampatra/wedding-website#51]
Hi, I found your site because I'm getting married and I want to make my own static site. I wanted to look for open-sourced examples first, and I appreciate that you were willing to share the code for your site with the world. It looks great.

There is one major issue, but it's a huge one... the GPL-3.0 license that you chose to include with your source code forces all derivative works to also openly publish their source code. This means that **all source code for all derivative works must be made publicly available, which means that hiding wedding details from the public is impossible**.

Unfortunately, this is a showstopper for me. I'm planning to put my own static site behind a password-protected gateway so that the world doesn't know all the details about my upcoming wedding. I only want to share these details with family and friends that have the password to the site. While I could clone your site and put it behind a password-protected gateway, it wouldn't really be private since anyone could find the source code (since it must be made public).

It's possible to password-protect static sites by using a Lambda authorizing function to access Cloudfront distributions in S3, and this is how I plan to make my own static site private (once it's developed).

Maybe you carefully chose the GPL-3.0 license for your own reasons, which is completely fine. It's your code, after all. But I want to bring this issue up because, as it currently stands, your open-sourced project means that anyone that uses your work in any capacity *must* also open-source their work. You published this source code *after* your wedding, and you therefore avoided privacy concerns that come with having your wedding details made public. **Anyone that wants to use your code to *build* a wedding site must expose their wedding details to the world.**

In my opinion, your project would provide more value to the community if it contained an MIT license, because the MIT license would allow anyone to clone your code, build their own site, keep the source code private, and host it with password protection.

**Comment by rampatra** [comment]
Thanks for your interest in my work. Please, go ahead and use this privately. As long as it's not commercially used, it should be okay I suppose. I will think about it and change the License in the future.

**Comment by Anshluthra1** [comment]
hi . how to build it? pls help me ram sir. if you see this

**Comment by rampatra** [comment]
@Anshluthra1 the build instructions are mentioned in the readme file. Just make sure you have npm and gulp installed on your system. You can google how to install them based on the OS you're using.

**Comment by Anshluthra1** [comment]
okay surely . last one. after i have gulped it, which folder should be brought into production, deployed to firebase or netlify?

**Comment by Anshluthra1** [comment]
<img width="1437" alt="Screenshot 2021-05-12 at 5 26 06 PM" src="https://user-images.githubusercontent.com/76260663/117971282-4d8bf580-b347-11eb-9af5-a3216445af30.png">


hi sir it got published, but it has random blank spaces like this, can you rectify
