### ISSUE TITLE
Email backend won't work

### ISSUE THREAD

**Issue by DavidGriffith** [rampatra/wedding-website#6]
Email backend won't work.  Tried following https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server.  Console reports "success", but nothing ever comes into my mailserver.  No connections.  Nothing.

**Comment by rampatra** [comment]
@DavidGriffith I think this question should go to the other repo (https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server). Also, please make sure that you have provided proper permissions to run the google script.
