### ISSUE TITLE
Can't Deploy Github Pages with All node_modules

### ISSUE THREAD

**Issue by jkaw** [rampatra/wedding-website#76]
Github pages will fail if you try to deploy with all of the node modules currently in your repo. 
Remove all but the necessary ones in the package.json
"animate.css": "^3.7.2",
"font-awesome": "^4.7.0",
"waypoints": "^4.0.1"

and the gulp related ones for development. But you probably should put some gulp info in the README as well so people know how to minimize/compile the js and sass files.

**Comment by sachinjogi** [comment]
@jkaw were you able to fix it? If yes, can you upload the package.json

**Comment by jkaw** [comment]
@sachinjogi the package json is correct. You just need to delete all folders in the node_modules folder except for the ones I listed from your fork.

In your local you might want to keep the gulp related ones if you plan on changing any js/css as those will need to be minimized.

**Comment by sachinjogi** [comment]
Right, actually it wasn't the issue with the package.json, author had pushed node modules to the repo which had some erroneous files. I jusr reverted it to an older commit and it fixed it.

**Comment by rampatra** [comment]
@sachinjogi `i recently updated older dependency versions to their latest ones. This shouldn't give you any issues. Make sure you do: `npm install` and `gulp build`.

**Comment by jkaw** [comment]
@rampatra can you remove the extra node folders from your master? It will prevent this from being able to deploy on pages otherwise. You can change the README to run the npm commands. Even your github pages deploy action failed with the latest commit.

**Comment by rampatra** [comment]
@jkaw it's deleted now. Users have to do `npm install` before running the website from now on.

**Comment by jkaw** [comment]
@rampatra if you delete the entire folder, you will lose a few node js libraries that the site needs to function properly. Check wedding.rampatra.com to see whats broken on your demo now. You need to keep the three folders I mentioned.

**Comment by rampatra** [comment]
@jkaw I do not understand. Why doesn't it work on github pages? Locally, this works fine. `npm install` command downloads all dependencies including the three that you have listed here and I see no issue.

**Comment by rampatra** [comment]
I tried even defining my own custom workflow file with build commands but still no luck.

Here is the workflow file for reference: https://github.com/rampatra/wedding-website/actions/runs/4298555939/workflow

**Comment by jkaw** [comment]
The problem is that the node_modules folder has too many unnecessary folders. The only ones you need for the website to function properly are:
animate.css
font-awesome
waypoints

The rest of them are not needed for the website to run. The extras that were in the node_modules folder caused the deployment tar to exceed the size limit for github pages. I will submit a merge request to restore things and you can take a look.

**Comment by jkaw** [comment]
check pull request #77.

In my personal fork I did this and my github pages works.

**Comment by rampatra** [comment]
I updated my workflow file with deploy instructions but I am seeing other issues now - https://github.com/rampatra/wedding-website/blob/master/.github/workflows/npm-gulp.yml

I will have to debug it later. But for now, the fallback technique in index.html is fine to make the website work on github pages.

**Comment by rampatra** [comment]
I have closed this issue and created a new ticket to handle it later - https://github.com/rampatra/wedding-website/issues/78
